Aggregate function
i-camp/i-smile-admin pull request #1
Opened 2018-06-26 05:42 UTC by anntoque

よろしくです

2018-06-26 08:27 UTC, nakahararuu requested changes

2018-06-26 08:27 UTC, nakahararuu commented on src/app/sort-player.ts
> +            .filter((obj, i, self) => self.findIndex(obj2 => obj2.id === obj.id) === i);
playerIdの重複を許さないようにスキーマを設計しています。
https://gist.github.com/nakahararuu/0a6a021b0d2cbb5be90d7bb566ea6129

playerの重複排除は不要な処理になるかと思いますー

2018-06-26 08:27 UTC, nakahararuu commented on src/app/sort-player.ts
> +            }
SortedPlayersList の定義を修正したことにより、photographerやsubjectは空配列で初期化できるようになったかと思います。空配列で初期化すればL56,57のフィルタ処理も不要になりそうですね。

2018-06-26 08:27 UTC, nakahararuu commented on .vscode/launch.json
> +            "program": "${workspaceFolder}/proxy.conf.js",
VSCodeで開発サーバを起動する設定ファイルだと思いますが、この内容だと多分正常に立ち上がりませんよね？
後で消しておきますねー

2018-06-26 08:27 UTC, nakahararuu commented on src/app/sort-player.ts
> +        name: string;
photographer, subject共にcountの追加をお願いしたかと思いますが対応してもらってもよろしいですか？

2018-06-27 21:18 UTC, anntoque commented on src/app/sort-player.ts
> +            .filter((obj, i, self) => self.findIndex(obj2 => obj2.id === obj.id) === i);
処理消して対応します

2018-06-27 21:20 UTC, anntoque commented on .vscode/launch.json
> +            "program": "${workspaceFolder}/proxy.conf.js",
よろしくお願いします！ignoreに含めておきます！

2018-06-27 21:23 UTC, anntoque commented on src/app/sort-player.ts
> +            }
から配列で対応してフィルタ処理を消します！

2018-06-27 21:26 UTC, anntoque commented on src/app/sort-player.ts
> +        name: string;
インターフェースにcountの追加とgame.tsのinterface RankingEventの修正で対応しました！

2018-06-28 01:14 UTC, nakahararuu approved these changes

2018-06-28 01:14 UTC, merged